import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/page/Header'
import Footer from '@/components/page/Footer'
import { CartProvider } from '@/context/CartContext'
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='uk'>
			{/* Оновлено на 'uk' */}
			<body>
				<CartProvider>
					{/* ✅ Тепер і Header, і Footer бачать useCart() */}
					<Header />
					<main>{children}</main> {/* Додано <main> для семантики */}
					<Footer />
					<Toaster position='top-right' />
				</CartProvider>
			</body>
		</html>
	)
}
